Convert indentation to spaces.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,10 +2,10 @@
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-	against=HEAD
+  against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=$(git hash-object -t tree /dev/null)
+  # Initial commit: diff against an empty tree object
+  against=$(git hash-object -t tree /dev/null)
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
@@ -19,20 +19,20 @@ exec 1>&2
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+  # Note that the use of brackets around a tr range is ok here, (it's
+  # even required, for portability to Solaris 10's /usr/bin/tr), since
+  # the square bracket bytes happen to fall in the designated range.
+  test $(git diff --cached --name-only --diff-filter=A -z $against |
+    LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
-	cat <<\EOF
+  cat <<\EOF
 Error: Attempt to add a non-ASCII file name.
 This can cause problems if you want to work with people on other platforms.
 To be portable it is advisable to rename the file.
 If you know what you are doing you can disable this check using:
   git config hooks.allownonascii true
 EOF
-	exit 1
+  exit 1
 fi
 
 # Run linters at this point to prevent commits that might break CI linters.
@@ -41,16 +41,16 @@ statusCode=$?
 echo "\n";
 
 if [ $statusCode != 0 ]; then
-	red=`tput setaf 1`
-	green=`tput setaf 2`
-	yellow=`tput setaf 3`
-	bold=`tput bold`
-	underline=`tput smul`
-	nounderline=`tput rmul`
-	reset=`tput sgr0`
-	echo "${red}${bold}Please resolve any ${underline}eslint${nounderline} errors shown above before committing.${reset}";
-	echo "${yellow}If you absolutely must commit, please use the ${green}--no-verify${yellow} option.${reset}"
-	exit 1
+  red=`tput setaf 1`
+  green=`tput setaf 2`
+  yellow=`tput setaf 3`
+  bold=`tput bold`
+  underline=`tput smul`
+  nounderline=`tput rmul`
+  reset=`tput sgr0`
+  echo "${red}${bold}Please resolve any ${underline}eslint${nounderline} errors shown above before committing.${reset}";
+  echo "${yellow}If you absolutely must commit, please use the ${green}--no-verify${yellow} option.${reset}"
+  exit 1
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
